version: "2"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: slack
    ports:
      - "3030:5432"
  web:
    image: jabro86/mixchat-server:latest
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      SERVER_URL: http://mixchat.westeurope.cloudapp.azure.com
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
  nginx:
    image: nginx
    networks:
      - webnet
    depends_on:
      - web
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./uploads:/uploads
    ports:
      - "80:80"
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet: